name: spgl1
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6.4
  - pip
  - numpy>=1.15.0
  - scipy
  - matplotlib
  - ipython
  - jupyter
  - pytest
  - Sphinx
  - numpydoc
  - pre-commit
  - autopep8
  - isort
  - black
  - pip:
    - pytest-runner
    - setuptools_scm
    - sphinx-rtd-theme
    - sphinx-gallery
    - nbsphinx
    - image
    - flake8
